### ISSUE TITLE
Adapter lässt sich nicht konfigurieren.

### ISSUE THREAD

**Issue by c1381ie** [AlGu1/ioBroker.hombot#1]
Hi,

der Adapter kann nicht konfiguriert werden. über den Cloud Adapter passen die Einstellungen leider wird kein Datenobjekt angelegt und auch nichts dargestellt. 

LG

**Comment by c1381ie** [comment]
Hi,

sorry klar mein Fehler. Bin noch neu hier in Github. Also hier die Angaben:

Welches System (Hardware, iobroker Installation)?
iobroker installiert auf ESXi, Hardware ist ein Dell Server System ioBroker ist in der Verison: 3.2.0 installiert.

Versionen der Adpater (Admin, js-Conroller, hombot)?
Admin: 3.2.0
js-Controller: 3.6.4
hombot: 0.0.5 

Was hat das mit "Cloud Adapter" zu tun?!?
Der Cloud Adapter war vor ein Paar tagen noch auf Admin2 und wurde nun auf Admin3 gehoben. Mit der Aussage wollte ich nur sagen das der Fehelr scheinbar unter Admin3 auftritt. Ich habe mal ein Bild angehängt. Daran erkennt man denke ich das Problem besser. 

LG
![23-04-_2018_09-04-45](https://user-images.githubusercontent.com/37777255/39111480-92b3fff4-46d5-11e8-908a-5883d610381f.jpg)

**Comment by c1381ie** [comment]
Hi noch ein Nachtrag...
also der Adapter läuft wenn man Ihn über Admin2 konfiguriert im ioBroker. Danach kann man auf Admin3 umschalten und alle Daten sind da. 

Ich habe testweise mein komplettes System neu erstellt und kann Sagen das es wohl an der Admin3 (bei Mir aktuell 3.4.0) Oberfläche liegt. 

Vielleicht kann man hier noch einen Hinweis geben das es nur damit läuft oder das ganze Updaten auf Admin3. 

LG

**Comment by AlGu1** [comment]
Der Adapter sollte jetzt auch mit Admin3 funktionieren. Danke für die Tests und die Info.

Viele Grüße
AlGu
